apiVersion: apps/v1
kind: Deployment
metadata:
  name: ragavgo-deployment
  labels:
    app: ragavgo
    backstage.io/kubernetes-id: ragavgo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ragavgo
  template:
    metadata:
      labels:
        app: ragavgo
        backstage.io/kubernetes-id: ragavgo
    spec:
      containers:
      - name: ragavgo
        image: samgabrail/ragavgo:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ragavgo-service
  labels:
    backstage.io/kubernetes-id: ragavgo
spec:
  type: LoadBalancer  
  selector:
    app: ragavgo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
